[package]
name = "brw"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

default = ["async-std"]

builder = []

[dependencies]
async-std = { version = "1.9.0", optional = true }
async-trait = "0.1.50"
flume = "0.10.7"
futures = "0.3.15"
log = "0.4.14"
tokio = { version = "1.7.1", features = ["rt-multi-thread"], optional = true }
